package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caissedepret generated by hbm2java
 */
public class Caissedepret  implements java.io.Serializable {


     private Integer idCaissedepret;
     private Projet projet;
     private Date datePret;
     private long montantDebloquer;
     private long interet;
     private Date dateDerniereTranche;
     private long penalite;
     private Date delaiDeGrace;
     private Set tranches = new HashSet(0);
     private Set dettes = new HashSet(0);
     private Set conventions = new HashSet(0);

    public Caissedepret() {
    }

	
    public Caissedepret(Projet projet, Date datePret, long montantDebloquer, long interet, Date dateDerniereTranche, long penalite, Date delaiDeGrace) {
        this.projet = projet;
        this.datePret = datePret;
        this.montantDebloquer = montantDebloquer;
        this.interet = interet;
        this.dateDerniereTranche = dateDerniereTranche;
        this.penalite = penalite;
        this.delaiDeGrace = delaiDeGrace;
    }
    public Caissedepret(Projet projet, Date datePret, long montantDebloquer, long interet, Date dateDerniereTranche, long penalite, Date delaiDeGrace, Set tranches, Set dettes, Set conventions) {
       this.projet = projet;
       this.datePret = datePret;
       this.montantDebloquer = montantDebloquer;
       this.interet = interet;
       this.dateDerniereTranche = dateDerniereTranche;
       this.penalite = penalite;
       this.delaiDeGrace = delaiDeGrace;
       this.tranches = tranches;
       this.dettes = dettes;
       this.conventions = conventions;
    }
   
    public Integer getIdCaissedepret() {
        return this.idCaissedepret;
    }
    
    public void setIdCaissedepret(Integer idCaissedepret) {
        this.idCaissedepret = idCaissedepret;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Date getDatePret() {
        return this.datePret;
    }
    
    public void setDatePret(Date datePret) {
        this.datePret = datePret;
    }
    public long getMontantDebloquer() {
        return this.montantDebloquer;
    }
    
    public void setMontantDebloquer(long montantDebloquer) {
        this.montantDebloquer = montantDebloquer;
    }
    public long getInteret() {
        return this.interet;
    }
    
    public void setInteret(long interet) {
        this.interet = interet;
    }
    public Date getDateDerniereTranche() {
        return this.dateDerniereTranche;
    }
    
    public void setDateDerniereTranche(Date dateDerniereTranche) {
        this.dateDerniereTranche = dateDerniereTranche;
    }
    public long getPenalite() {
        return this.penalite;
    }
    
    public void setPenalite(long penalite) {
        this.penalite = penalite;
    }
    public Date getDelaiDeGrace() {
        return this.delaiDeGrace;
    }
    
    public void setDelaiDeGrace(Date delaiDeGrace) {
        this.delaiDeGrace = delaiDeGrace;
    }
    public Set getTranches() {
        return this.tranches;
    }
    
    public void setTranches(Set tranches) {
        this.tranches = tranches;
    }
    public Set getDettes() {
        return this.dettes;
    }
    
    public void setDettes(Set dettes) {
        this.dettes = dettes;
    }
    public Set getConventions() {
        return this.conventions;
    }
    
    public void setConventions(Set conventions) {
        this.conventions = conventions;
    }




}


