package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Dette generated by hbm2java
 */
public class Dette  implements java.io.Serializable {


     private Integer idDette;
     private Caissedepret caissedepret;
     private Societe societe;
     private long detteBrute;
     private long montantPaye;
     private long montantRestant;
     private String etat;
     private Date dateCreation;
     private String coleur;
     private int annee;
     private Set conventions = new HashSet(0);

    public Dette() {
    }

	
    public Dette(long detteBrute, long montantPaye, long montantRestant, String etat, Date dateCreation, int annee) {
        this.detteBrute = detteBrute;
        this.montantPaye = montantPaye;
        this.montantRestant = montantRestant;
        this.etat = etat;
        this.dateCreation = dateCreation;
        this.annee = annee;
    }
    public Dette(Caissedepret caissedepret, Societe societe, long detteBrute, long montantPaye, long montantRestant, String etat, Date dateCreation, String coleur, int annee, Set conventions) {
       this.caissedepret = caissedepret;
       this.societe = societe;
       this.detteBrute = detteBrute;
       this.montantPaye = montantPaye;
       this.montantRestant = montantRestant;
       this.etat = etat;
       this.dateCreation = dateCreation;
       this.coleur = coleur;
       this.annee = annee;
       this.conventions = conventions;
    }
   
    public Integer getIdDette() {
        return this.idDette;
    }
    
    public void setIdDette(Integer idDette) {
        this.idDette = idDette;
    }
    public Caissedepret getCaissedepret() {
        return this.caissedepret;
    }
    
    public void setCaissedepret(Caissedepret caissedepret) {
        this.caissedepret = caissedepret;
    }
    public Societe getSociete() {
        return this.societe;
    }
    
    public void setSociete(Societe societe) {
        this.societe = societe;
    }
    public long getDetteBrute() {
        return this.detteBrute;
    }
    
    public void setDetteBrute(long detteBrute) {
        this.detteBrute = detteBrute;
    }
    public long getMontantPaye() {
        return this.montantPaye;
    }
    
    public void setMontantPaye(long montantPaye) {
        this.montantPaye = montantPaye;
    }
    public long getMontantRestant() {
        return this.montantRestant;
    }
    
    public void setMontantRestant(long montantRestant) {
        this.montantRestant = montantRestant;
    }
    public String getEtat() {
        return this.etat;
    }
    
    public void setEtat(String etat) {
        this.etat = etat;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }
    public String getColeur() {
        return this.coleur;
    }
    
    public void setColeur(String coleur) {
        this.coleur = coleur;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }
    public Set getConventions() {
        return this.conventions;
    }
    
    public void setConventions(Set conventions) {
        this.conventions = conventions;
    }




}


