package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private Integer idFacture;
     private Projet projet;
     private Societe societe;
     private int numFacture;
     private Date dateArrive;
     private Date datePaiement;
     private long montantFacture;
     private String detail;
     private int annee;

    public Facture() {
    }

    public Facture(Projet projet, Societe societe, int numFacture, Date dateArrive, Date datePaiement, long montantFacture, String detail, int annee) {
       this.projet = projet;
       this.societe = societe;
       this.numFacture = numFacture;
       this.dateArrive = dateArrive;
       this.datePaiement = datePaiement;
       this.montantFacture = montantFacture;
       this.detail = detail;
       this.annee = annee;
    }
   
    public Integer getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(Integer idFacture) {
        this.idFacture = idFacture;
    }
    public Projet getProjet() {
        return this.projet;
    }
    
    public void setProjet(Projet projet) {
        this.projet = projet;
    }
    public Societe getSociete() {
        return this.societe;
    }
    
    public void setSociete(Societe societe) {
        this.societe = societe;
    }
    public int getNumFacture() {
        return this.numFacture;
    }
    
    public void setNumFacture(int numFacture) {
        this.numFacture = numFacture;
    }
    public Date getDateArrive() {
        return this.dateArrive;
    }
    
    public void setDateArrive(Date dateArrive) {
        this.dateArrive = dateArrive;
    }
    public Date getDatePaiement() {
        return this.datePaiement;
    }
    
    public void setDatePaiement(Date datePaiement) {
        this.datePaiement = datePaiement;
    }
    public long getMontantFacture() {
        return this.montantFacture;
    }
    
    public void setMontantFacture(long montantFacture) {
        this.montantFacture = montantFacture;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public int getAnnee() {
        return this.annee;
    }
    
    public void setAnnee(int annee) {
        this.annee = annee;
    }




}


