package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1



/**
 * Service generated by hbm2java
 */
public class Service  implements java.io.Serializable {


     private Integer idService;
     private String role;
     private String motDePasse;

    public Service() {
    }

    public Service(String role, String motDePasse) {
       this.role = role;
       this.motDePasse = motDePasse;
    }
   
    public Integer getIdService() {
        return this.idService;
    }
    
    public void setIdService(Integer idService) {
        this.idService = idService;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getMotDePasse() {
        return this.motDePasse;
    }
    
    public void setMotDePasse(String motDePasse) {
        this.motDePasse = motDePasse;
    }




}


