package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Societe generated by hbm2java
 */
public class Societe  implements java.io.Serializable {


     private Integer idSociete;
     private String nomSociete;
     private String adresseSociete;
     private String nature;
     private String contactSociete;
     private Set dettes = new HashSet(0);
     private Set conventions = new HashSet(0);
     private Set factures = new HashSet(0);

    public Societe() {
    }

	
    public Societe(String nomSociete, String adresseSociete, String nature, String contactSociete) {
        this.nomSociete = nomSociete;
        this.adresseSociete = adresseSociete;
        this.nature = nature;
        this.contactSociete = contactSociete;
    }
    public Societe(String nomSociete, String adresseSociete, String nature, String contactSociete, Set dettes, Set conventions, Set factures) {
       this.nomSociete = nomSociete;
       this.adresseSociete = adresseSociete;
       this.nature = nature;
       this.contactSociete = contactSociete;
       this.dettes = dettes;
       this.conventions = conventions;
       this.factures = factures;
    }
   
    public Integer getIdSociete() {
        return this.idSociete;
    }
    
    public void setIdSociete(Integer idSociete) {
        this.idSociete = idSociete;
    }
    public String getNomSociete() {
        return this.nomSociete;
    }
    
    public void setNomSociete(String nomSociete) {
        this.nomSociete = nomSociete;
    }
    public String getAdresseSociete() {
        return this.adresseSociete;
    }
    
    public void setAdresseSociete(String adresseSociete) {
        this.adresseSociete = adresseSociete;
    }
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }
    public String getContactSociete() {
        return this.contactSociete;
    }
    
    public void setContactSociete(String contactSociete) {
        this.contactSociete = contactSociete;
    }
    public Set getDettes() {
        return this.dettes;
    }
    
    public void setDettes(Set dettes) {
        this.dettes = dettes;
    }
    public Set getConventions() {
        return this.conventions;
    }
    
    public void setConventions(Set conventions) {
        this.conventions = conventions;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }




}


