package Model;
// Generated 16 mai 2016 23:18:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Tranche generated by hbm2java
 */
public class Tranche  implements java.io.Serializable {


     private Integer idTranche;
     private Caissedepret caissedepret;
     private int numTranche;
     private long montantTranche;
     private Date dateArriveTranche;

    public Tranche() {
    }

    public Tranche(Caissedepret caissedepret, int numTranche, long montantTranche, Date dateArriveTranche) {
       this.caissedepret = caissedepret;
       this.numTranche = numTranche;
       this.montantTranche = montantTranche;
       this.dateArriveTranche = dateArriveTranche;
    }
   
    public Integer getIdTranche() {
        return this.idTranche;
    }
    
    public void setIdTranche(Integer idTranche) {
        this.idTranche = idTranche;
    }
    public Caissedepret getCaissedepret() {
        return this.caissedepret;
    }
    
    public void setCaissedepret(Caissedepret caissedepret) {
        this.caissedepret = caissedepret;
    }
    public int getNumTranche() {
        return this.numTranche;
    }
    
    public void setNumTranche(int numTranche) {
        this.numTranche = numTranche;
    }
    public long getMontantTranche() {
        return this.montantTranche;
    }
    
    public void setMontantTranche(long montantTranche) {
        this.montantTranche = montantTranche;
    }
    public Date getDateArriveTranche() {
        return this.dateArriveTranche;
    }
    
    public void setDateArriveTranche(Date dateArriveTranche) {
        this.dateArriveTranche = dateArriveTranche;
    }




}


